CREATE TABLE [dbo].[Account]
(
	[AcctNo] INT NOT NULL,
	[Fname] NVARCHAR(15) NOT NULL,
	[Lname] NVARCHAR(15) NOT NULL,
	[CreditLimit] MONEY NOT NULL,
	[Balance] MONEY NOT NULL,
	CONSTRAINT PK_ACCOUNT PRIMARY KEY (AcctNo),
	CONSTRAINT UC_ACCOUNT UNIQUE (Fname, Lname),
	CONSTRAINT CHK_CREDITLIMIT CHECK(CreditLimit < $0),
	CONSTRAINT CHK_BALANCE CHECK(Balance > CreditLimit)
)
