CREATE TABLE [dbo].[Log]
(
	[OrigAcct] INT NOT NULL,
	[LogDateTime] DATETIME NOT NULL,
	[RecAcct] INT NULL,
	[Amount] MONEY NOT NULL,
	CONSTRAINT PK_LOG PRIMARY KEY (OrigAcct, LogDateTime),
	CONSTRAINT FK_LOG_ORIGACCT FOREIGN KEY (OrigAcct) REFERENCES Account (AcctNo),
	CONSTRAINT FK_LOG_RECACCT FOREIGN KEY (RecAcct) REFERENCES Account (AcctNo)
)
